### ISSUE TITLE
Looking forward to EgoLocate

### ISSUE THREAD

**Issue by SlimeVRX** [Xinyu-Yi/EgoLocate#1]
Hi @Xinyu-Yi 

I look forward to your research. Can you reveal what EgoLocate research is?

Thank you very much!

**Comment by SlimeVRX** [comment]
I lack ideas for my work, and your work is an excellent motivation for me!

**Comment by Xinyu-Yi** [comment]
Hi, thanks for your interest. It's still a work on human mocap from 6 IMUs. We use an additional body-worn phone camera to solve the drift problem of inertial mocap by combining it with SLAM, or scene reconstruction. We will make this public soon.

**Comment by SlimeVRX** [comment]
Hi @Xinyu-Yi 

Your work is amazing!
I will also work hard to achieve my goal.

**Comment by NoLoPhe** [comment]
Hi,

I just read the EgoLocate article. Thanks for your team's work!
