### ISSUE TITLE
Could you please provide the datasets which can run orbslam3 and imu network shown in the video

### ISSUE THREAD

**Issue by shibowing** [Xinyu-Yi/EgoLocate#5]
Hi all, 

Thanks for contribution. However, I cannot find good datasets to run your code. I am wondering if you can share the datasets same as you shown in the video and make this project could be runnable ? 

Thank you so much for the help! Hope we can get your reply soon! 

Best

**Comment by Xinyu-Yi** [comment]
Hi, I have uploaded the processed test dataset. You can check readme._
