### ISSUE TITLE
TotalCapture synthetic data head camera position

### ISSUE THREAD

**Issue by HandiYin** [Xinyu-Yi/EgoLocate#7]
Hi! Thanks for sharing your code and synthetic totalcpature data for testing. 

While running your script for totalcapture testing, I had a question about the synthetic camera position. I traced down to Tracking.cc file and found the rotation between head and camera was considered as an identity matrix. Also the scale can be set as 1 (if using standard beta from my understanding). But I didn't find information about the transition setting, which I think is alos necessary to make a calibration.

May I know where do you put the optical center of the virtual camera in the synthetic data? Is it consistent with the SMPL head joint or some other vertice position?

Thank you!

**Comment by Xinyu-Yi** [comment]
Hi, for the TotalCapture dataset, I put the camera at the SMPL head joint, with the same orientation (facing direction) as the SMPL head. I forgot how the camera coordinate frame is defined. Its y-axis is either straight up or down (according to the coordinate definition).

I have forgotten why I set the scale to 1. Maybe in the walking-in-a-curve calibration I can calculate the scale.

**Comment by HandiYin** [comment]
Thank you! I think this solves my problem. I had run some tests on EgoLocate and it's really a great work! 
Best wishes!
